# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"

  - package-ecosystem: "npm"
    directory: "/shop-app"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      aws:
        patterns:
          - "@aws-sdk/*"
      mui-emotion:
        patterns:
          - "@emotion/*"
          - "@mui/*"
      redux:
        patterns:
          - "*redux*"
      types:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
      vite:
        patterns:
          - "*vite*"

  - package-ecosystem: "pip"
    directory: "/microservices/iam-old"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      boto:
        patterns:
          - "boto3"
          - "botocore"
          - "s3transfer"

  - package-ecosystem: "pip"
    directory: "/microservices/store"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      boto:
        patterns:
          - "boto3"
          - "botocore"
          - "s3transfer"
      moto:
        patterns:
          - "moto"
          - "py-partiql-parser"
