version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - cd shop-app # the shell instance is saved every build command
      - echo Build started on `date`
      - npm ci
  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building app
      - npm run build
  post_build:
    commands:
      # Delete the old code in S3 before uploading the new code
      - aws s3 rm s3://$ARTIFACT_BUCKET --recursive
      - echo Build completed on `date`
artifacts:
  base-directory: "shop-app/dist"
  files:
    - "**/*"
