version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd shop-app # the shell instance is saved every build command
      - echo Build started on `date`
      - echo Node version `node -v`
      - npm ci
  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building app
      - npm run build
    # Don't go to post_build if the build failed
    on-failure: ABORT
  post_build:
    commands:
      # Only delete/update files that differ in size (usually the CSS & JS files)
      # Ignores timestamps & minimizes the number of delete markers and noncurrent versions
      - aws s3 sync dist s3://$ARTIFACT_BUCKET --size-only --delete
      - echo Build completed on `date`
