AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  A stack to host the frontend and configure the backend of the AWS Shopping App
#Metadata
Parameters:
  ReactAppBucketName:
    Type: String
    Description: The name of the S3 bucket to store the React code
    Default: aws-shop-bucket-jlkafn93hvo0a3f
#Rules
#Mappings
#Conditions
#Transform
Resources:
  # IAM users/roles
  # Frontend Developer
  # Backend Developer
  # Database Administrator
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Admins
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  DeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Developers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/SystemAdministrator
  DatabaseAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DatabaseAdmins
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
  # Create an IdP for GitHub to use in workflows
  GitHubRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GitHubOIDC
            Condition:
              # aud = audience, sub = subject
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:Abhiek187/aws-shop:*
      ManagedPolicyArns:
        # A list of policies required for every workflow (max 10)
        # The shortest managed policies will move to a consolidated customer policy
        - !Ref GitHubRemainingPolicy
        # CloudFormation (need read access to detect drift & write access to update resources)
        - "arn:aws:iam::aws:policy/CloudFrontFullAccess" # 31
        - "arn:aws:iam::aws:policy/IAMFullAccess" # 22
        # React
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess" # 133
        # Microservices
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess" # 108
        # SAM
        - "arn:aws:iam::aws:policy/AWSLambda_FullAccess" # 52
        - "arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess" # 83
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess" # 36
  GitHubRemainingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      guard:
        SuppressedRules:
          - IAM_POLICY_NO_STATEMENTS_WITH_FULL_ACCESS # need write access for CloudFormation
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudFormationFullAccess
            Effect: Allow
            Action:
              - "cloudformation:*"
            Resource: "*"
          - Sid: AmazonSNSFullAccess
            Effect: Allow
            Action:
              - "sns:*"
            Resource: "*"
          - Sid: AmazonS3FullAccess
            Effect: Allow
            Action:
              - "s3:*"
              - "s3-object-lambda:*"
            Resource: "*"
          - Sid: AmazonAPIGatewayAdministrator
            Effect: Allow
            Action:
              - "apigateway:*"
            Resource: "arn:aws:apigateway:*::/*"
  GitHubOIDC:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
  # Allow CodeBuild to upload objects to S3
  # https://docs.aws.amazon.com/codebuild/latest/userguide/setting-up.html#setting-up-service-role
  CodeBuildPolicy:
    Type: AWS::IAM::ManagedPolicy
    Metadata:
      guard:
        SuppressedRules:
          # The same suppressed rule must be defined here due to a bug with cfn-guard:
          # https://github.com/aws-cloudformation/aws-guard-rules-registry/issues/246
          - IAM_POLICY_NO_STATEMENTS_WITH_FULL_ACCESS
    Properties:
      ManagedPolicyName: CodeBuildAccess
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CloudWatchLogsPolicy
            Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "*"
          - Sid: S3ObjectPolicy
            Effect: Allow
            Action:
              - "s3:DeleteObject"
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:PutObject"
            Resource:
              - !GetAtt ReactAppBucket.Arn
              - !Sub "${ReactAppBucket.Arn}/*"
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Ref CodeBuildPolicy
  # CodePipeline (or just CodeBuild for now)
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    # DependsOn: CodeBuildSourceCredential
    Properties:
      Name: AWSShopBuild
      Description: A project that builds and deploys the AWS Shopping App
      Source:
        Auth:
          Type: OAUTH
        # Directions to let GitHub authorize CodeBuild:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-location
        Location: https://github.com/Abhiek187/aws-shop.git # not required if using CodePipeline
        Type: GITHUB
        ReportBuildStatus: true
      ServiceRole: !GetAtt CodeBuildRole.Arn
      # Upload the build to the S3 bucket
      Artifacts:
        Location: !Ref ReactAppBucketName
        Name: "/" # store the build in the root directory of the bucket (not zipped)
        Type: S3
        # Don't override S3's default SSE-S3 encryption with a KMS key
        # (will prevent the website from being accessible)
        EncryptionDisabled: true
      Environment:
        # Make sure the image supports the runtime in the buildspec:
        # https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
        Type: ARM_CONTAINER
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0 # Amazon Linux 2 ARM image
        ComputeType: BUILD_GENERAL1_SMALL # free tier eligible
        EnvironmentVariables:
          - Name: CI
            Value: "true"
          - Name: ARTIFACT_BUCKET
            Value: !Ref ReactAppBucket
      BadgeEnabled: true # show a badge of the build status on GitHub, remove if using CodePipeline
      TimeoutInMinutes: 5 # important to limit build minutes/month (default: 60)
  # Get the PAT from Parameter Store to let CodeBuild authenticate with GitHub
  # ssm-secure only works with a limited number of resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#template-parameters-dynamic-patterns-resources
  # CodeBuildSourceCredential:
  #   Type: AWS::CodeBuild::SourceCredential
  #   Properties:
  #     Token: "{{resolve:ssm-secure:GitHubToken}}" # must be created outside CloudFormation
  #     ServerType: GITHUB
  #     AuthType: PERSONAL_ACCESS_TOKEN
  # CloudWatch
  # X-Ray
  ### Frontend ###
  # S3 bucket
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SuppressedRules:
          # Reliability suppressions
          - S3_BUCKET_REPLICATION_ENABLED # stay within 435 MB
          - S3_BUCKET_DEFAULT_LOCK_ENABLED # objects can be overwritten regularly
    # Can't delete an S3 bucket until all its objects are deleted
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref ReactAppBucketName
      # Buckets and objects are encrypted by default
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private # don't give public access to the S3 bucket directly
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: !Ref ReactAppBucketName
      # Some access settings need to be enabled to add bucket policies
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true # set to false when creating a bucket policy
        IgnorePublicAcls: true
        RestrictPublicBuckets: true # set to false when creating a bucket policy
      VersioningConfiguration:
        Status: Enabled
      # Save money by deleting older copies of objects
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersionsRule
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
  ReactAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Metadata:
      guard:
        SuppressedRules:
          - S3_BUCKET_SSL_REQUESTS_ONLY # Resource: "*" isn't valid
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Only allow CloudFront to access the S3 bucket
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#create-oac-overview-s3
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - "s3:GetObject"
            Resource: !Sub "${ReactAppBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution.Id}"
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt ReactAppBucket.Arn
              - !Sub "${ReactAppBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false
  LoggingBucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SuppressedRules:
          # Reliability suppressions
          - S3_BUCKET_REPLICATION_ENABLED # stay within 435 MB
          # Security suppressions
          - S3_BUCKET_LOGGING_ENABLED # this is a logging bucket
    # Can't delete an S3 bucket until all its objects are deleted
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      # Some access settings need to be enabled to add bucket policies
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true # set to false when creating a bucket policy
        IgnorePublicAcls: true
        RestrictPublicBuckets: true # set to false when creating a bucket policy
      VersioningConfiguration:
        Status: Enabled
      # Save money by deleting older copies of objects
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersionsRule
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
      # Enable WORM (write once, read many)
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: GOVERNANCE # more lax than compliance mode
            Days: 30
  # CloudFront
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt ReactAppBucket.DomainName
            Id: ReactAppS3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: true # required
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultRootObject: index.html
        DefaultCacheBehavior: # required
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: ReactAppS3Origin
          CachePolicyId: !Ref CloudFrontCachePolicy
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100 # only use edge locations in North America, Europe, and Israel
        # CustomErrorResponses:
        #   - ErrorCachingMinTTL: 300 # 5 minutes
        #     ErrorCode: 403
        #     ResponseCode: 404
        #     ResponsePagePath: error.html
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: AWS Shopping App Origin Access Control
        Name: ReactAppOAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  CloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        # TTL in seconds
        DefaultTTL: 86400 # 1 day
        MaxTTL: 31536000 # 1 year
        MinTTL: 86400
        Name: ReactAppCachePolicy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          # Brotli has better compression than gzip
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
  ### Backend ###
  # API Gateway
  # SQS
  # Lambda
  # DynamoDB
  # Parameter Store
  # CloudFormation doesn't support creating a SecureString parameter type
  # Cognito
Outputs:
  WebsiteURL:
    Description: URL for the website hosted on S3
    Value: !GetAtt ReactAppBucket.WebsiteURL
  CloudFrontURL:
    Description: The URL of the React app hosted over HTTPS using CloudFront
    Value: !Sub "https://${CloudFrontDistribution.DomainName}/"
  GitHubRoleArn:
    Value: !GetAtt GitHubRole.Arn
