version = 0.1
[default.deploy.parameters]
stack_name = "IAM-Old-Stack"
resolve_s3 = true
s3_prefix = "IAM-Old-Stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ParameterKey=Email,UsePreviousValue=true"
tags = "AppManagerCFNStackKey=arn:aws:cloudformation:us-east-1:701157632481:stack/IAM-Old-Stack/0cd4a990-f910-11ed-86c8-0ec36529a8bd"
