AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
#Globals
Description: >-
  A stack that sends a reminder to users whenever their access key needs to be rotated
#Metadata
#Parameters
#Rules
#Mappings
#Conditions
Resources:
  # Lambda
  LambdaFunction:
    # Creates AWS::Lambda::Permission/Function, AWS::IAM::Role
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip # zip files run faster than container images
      CodeUri: src/
      Handler: app.handler
      Runtime: python3.8 # see https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
      Architectures:
        - arm64
      Description: Check the age of access keys for IAM users and send emails to an SNS topic
      Events:
        ScheduleEvent:
          # Schedule = AWS::Events::Rule, ScheduleV2 = AWS::Scheduler::Schedule
          Type: ScheduleV2
          Properties:
            Description: Check the age of access keys every day
            # You can't use * in both day-of-month [3] and day-of-week [5]
            ScheduleExpression: "cron(0 0 * * ?)" # run every day at midnight UTC
            State: ENABLED
      FunctionName: iam-old-handler
      Policies:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        # SAM policy templates:
        # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopic.TopicName
      # 128 MB of memory allocated by default
      # Automatically update the runtime version
      # Timeout after 3 seconds
      Environment:
        Variables:
          TopicArn: !Ref SNSTopic
  # SNS
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      # Encrypt using the default SNS SSE key
      # Key aliases: aws kms list-aliases
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: achaudhuri2011@yahoo.com
          Protocol: email
      TopicName: RotateAccessKeys
Outputs:
  SNSTopicArn:
    Description: SNS Topic ARN
    Value: !Ref SNSTopic
