name: CloudFormation CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "**.yaml"
      - ".github/workflows/cfn.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.yaml"
      - ".github/workflows/cfn.yml"

env:
  STACK_NAME: AWS-Shop-Frontend-Stack
  STACK_FILE: cloudformation.yaml

# Required to use the AWS CLI
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://${{ env.STACK_FILE }}

      - name: Detect Stack Drift
        run: |
          chmod u+x detect-cfn-drift.sh
          ./detect-cfn-drift.sh

      - name: Install cfn-guard
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
          echo "~/.guard/bin" >> $GITHUB_PATH

      # Run checks based on AWS's well-architected security & reliability pillars
      - name: Check for Vulnerabilities using cfn-guard
        run: >-
          cfn-guard validate --show-summary fail --output-format single-line-summary
          --data ${{ env.STACK_FILE }} --rules cfn-guard-rules/

  # If the tests were successful and we're pushing to main, create/update the stack
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          template: ${{ env.STACK_FILE }}
          no-fail-on-empty-changeset: "1"
