name: CloudFormation CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "**.yaml"
      - ".github/workflows/cfn.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.yaml"
      - ".github/workflows/cfn.yml"

env:
  AWS_REGION: us-east-1
  STACK_NAME: AWS-Shop-Frontend-Stack
  STACK_FILE: cloudformation.yaml
  CHANGE_SET: Change-Set

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: aws --version && aws sts get-caller-identity

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://${{ env.STACK_FILE }}

      - name: Detect Stack Drift
        run: aws cloudformation detect-stack-drift --stack-name ${{ env.STACK_NAME }}

      - name: Check for Vulnerabilities using cfn-guard
        uses: grolston/guard-action@main
        with:
          data_directory: "."
          rule_set: "wa-Security-Pillar"

      - name: Create a Change Set
        run: >-
          aws cloudformation create-change-set
          --stack-name ${{ env.STACK_NAME }}
          --change-set-name ${{ env.CHANGE_SET }}
          --template-body file://${{ env.STACK_FILE }}
          --capabilities CAPABILITY_NAMED_IAM

  # If the tests were successful and we're pushing to main, deploy the change set
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          template: ${{ env.STACK_FILE }}
