# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "shop-app/**"
      - ".github/workflows/node.js.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "shop-app/**"
      - ".github/workflows/node.js.yml"

env:
  CODEBUILD_PROJECT: AWSShopBuild

# Required to use the AWS CLI
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./shop-app

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./shop-app/package-lock.json"
      - run: npm ci
      - run: npm test

  # If the tests were successful and we're pushing to main, deploy to S3 using CodeBuild
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.CODEBUILD_PROJECT }}
