# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "microservices/store/**"
      - "microservices/iam-old/**"
      - ".github/workflows/python-app.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "microservices/store/**"
      - "microservices/iam-old/**"
      - ".github/workflows/python-app.yml"

# Required to use the AWS CLI
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./microservices/store

    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
        # See supported Python release schedule at https://devguide.python.org/versions/

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest

  # If the tests were successful and we're pushing to main, deploy using SAM
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    defaults:
      run:
        working-directory: ./microservices/store

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      # Build inside Docker containers
      - run: sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
